/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate persona-conditioned drafts
         * @description Synchronous draft generation. Draft count depends on the post:
         *     1 for a forum/Discussion reply, 2 for Gratitude (Empathetic +
         *     Goal-oriented), 3 for other activity posts.
         *
         *     Pipeline (server-side):
         *     1. Input safety filter (crisis lexicon). Crisis content returns a
         *        safety-signposting draft set instead of model output.
         *     2. Memory retrieval — chronological + activity-type from
         *        `memory.sqlite` for this `(participant_id, cohort_id)`.
         *     3. Engagement fingerprint — read panel.parquet via the dropout
         *        sister service or local mount; emit one-line summary.
         *     4. One independent decode per persona from the fine-tuned SLM with
         *        style suffixes + cross-draft n-gram blocking.
         *     5. MI-policy gate — each draft is cleaned and checked against the
         *        HOPE hard rules (no diagnostic language, no medication/dosage,
         *        no URLs). A violating draft is regenerated up to two times,
         *        keeping the attempt with the fewest violations. Any violation
         *        that still survives is returned in the draft's `mi_violations`
         *        so the dashboard can warn; the draft is not silently dropped.
         *     6. Grounding check (when `HOPE_GROUNDING_CHECK=1`) — the model judges
         *        each draft against the post. A draft that mentions something the
         *        post does not say is regenerated within the same repair budget;
         *        one that is still ungrounded is returned with
         *        `grounding: ungrounded` rather than dropped.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RichGenerateRequest"];
                };
            };
            responses: {
                /** @description Drafts generated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenerateResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
                /**
                 * @description The decode queue is full. One process serves one model, so
                 *     requests are serialized; past `HOPE_GEN_MAX_QUEUE` waiters
                 *     the service refuses rather than queueing invisibly. Clients
                 *     should retry — `code` is `generation_busy`, distinguishing
                 *     this from an unavailable service, and `Retry-After` suggests
                 *     how long to wait.
                 */
                503: {
                    headers: {
                        /** @description Suggested seconds before retrying. */
                        "Retry-After"?: number;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                            /** @enum {string} */
                            code?: "generation_busy";
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write a participant post to memory (idempotent)
         * @description Called by the HOPE MOVE platform webhook on every new participant
         *     post, OR by the JSON-reconcile cron during catch-up. Idempotent on
         *     `activity_id` — replays are safe.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MemoryPostRequest"];
                };
            };
            responses: {
                /** @description Stored or deduped. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryWriteResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write a facilitator reply to memory (idempotent)
         * @description Called by the HOPE MOVE platform webhook when a facilitator replies
         *     via the platform's own UI (not via our dashboard — those replies
         *     are written directly via the HITL fast-path on `/event`).
         *     Idempotent on `comment_id`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MemoryReplyRequest"];
                };
            };
            responses: {
                /** @description Stored or deduped. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryWriteResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk write — used for reconciliation and one-off backfill */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MemoryBatchRequest"];
                };
            };
            responses: {
                /** @description Batch processed; counts and per-item errors returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryBatchResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/post/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Right-to-erasure — hard delete a post and its associated reply rows */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    activity_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "deleted";
                            rows_affected: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug — show what the retriever sees for a participant
         * @description Admin / debug only. Returns the rows the chronological retriever would surface for the given participant within the given cohort.
         */
        get: {
            parameters: {
                query?: {
                    cohort_id?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    participant_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Memory entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryEntry"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture facilitator thumbs-up/down on a draft
         * @description Independent of any send action. A facilitator may thumbs-up a draft
         *     they did not pick this time (signal: "good draft, not the one I
         *     needed today") or thumbs-down a draft they edited and sent. This is
         *     the high-value KTO unary signal.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ThumbRequest"];
                };
            };
            responses: {
                /** @description Thumb recorded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AckResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Final action on a draft set (accept / edit / reject / flag)
         * @description Records the facilitator's eventual decision against a draft set.
         *     Side effect for action ∈ {accept, edit}: the `sent_text` is written
         *     to memory via the HITL fast-path so subsequent `/generate` calls
         *     see it within milliseconds (without waiting for the platform
         *     webhook). Edit distance to the chosen draft body is computed and
         *     stored on the matching `hitl_drafts` row.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventRequest"];
                };
            };
            responses: {
                /** @description Event recorded; memory updated when applicable. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AckResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/backfill-from-json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One-off memory bootstrap (not implemented in-service)
         * @description Not implemented as an HTTP endpoint — always returns 501. Backfill
         *     from the platform JSON exports is a standalone CLI
         *     (`python -m src.sync.backfill`) run at deploy time or after a memory
         *     DB rebuild, so the participant exports never need to be uploaded to
         *     the service. Kept in the spec to document the 501 for callers.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Restrict backfill to a single cohort (e.g. 1680 for IIH demo). */
                    cohort_id?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                401: components["responses"]["Unauthorized"];
                /** @description Not implemented — use the standalone backfill CLI. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check (no auth) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service status. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service + model version (no auth) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Version info. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus scrape endpoint
         * @description Prometheus exposition format. Currently exposes a single
         *     `hope_service_up` gauge — a liveness signal, not request/latency
         *     histograms. Kept for scrape compatibility.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus metrics. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Landing JSON (no auth)
         * @description Service identity; also satisfies the HF Space root probe.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service identity. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the adapters the model picker offers (no auth)
         * @description Returns the published Hub adapters in `HOSTED_MODELS` plus the id
         *     currently loaded. Read-open by design: the dashboard reads it on
         *     every page load to populate its dropdown.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current adapter + the switchable roster. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Hub id of the adapter loaded right now. */
                            current: string;
                            options: {
                                model_id?: string;
                                label?: string;
                            }[];
                            /**
                             * @description True when the deployment sets `HOPE_MODEL_LOCKED`.
                             *     The adapter is fixed: `POST /admin/model` returns
                             *     409, and the dashboard renders a read-only model
                             *     label instead of a picker.
                             * @default false
                             */
                            pinned: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hot-swap the live adapter
         * @description Unloads the current adapter and loads the requested one
         *     (~15–30 s on the Space GPU). Server-side global state — the swap
         *     affects every concurrent caller. HMAC-gated: a rogue swap is a
         *     denial-of-service vector.
         *
         *     Waits for any in-flight decode before unloading, so a swap
         *     cannot pull weights out from under a running generation.
         *     Returns 409 when the deployment pins its model.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description A Hub id from `/admin/models` options. */
                        model_id: string;
                    };
                };
            };
            responses: {
                /** @description Swap complete. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            current?: string;
                            previous?: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /**
                 * @description Model switching is locked on this deployment
                 *     (`HOPE_MODEL_LOCKED`). Production deployments serve one
                 *     pinned adapter; the switcher is for research.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/text/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 2–3 sentence engagement summary for the detail panel
         * @description Non-draft text: a third-person summary of one participant's
         *     engagement state for the facilitator's reference. No participant
         *     free-text in the request, so the input filter is a no-op; output is
         *     run through the same MI output filter as `/generate`. Honours
         *     `HOPE_DISABLE_GENERATION=1` with a deterministic stub.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TextGenResponse"];
                };
            };
            responses: {
                /** @description Summary text. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TextGenResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/text/coaching": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One tactical coaching suggestion for the facilitator
         * @description One concrete next step the facilitator can take with this
         *     participant. Recent post snippets, if provided, are run through the
         *     input safety filter; output through the MI output filter. Honours
         *     `HOPE_DISABLE_GENERATION=1`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Coaching text. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TextGenResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/text/polish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Polish a facilitator's draft note for tone / clarity
         * @description Rewrites a facilitator-authored draft for tone and clarity without
         *     changing its meaning. The draft can quote a participant, so it is
         *     run through the input safety filter; output through the MI output
         *     filter. Honours `HOPE_DISABLE_GENERATION=1` by returning the draft
         *     unchanged.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        draft_text: string;
                        participant_id: number;
                        /**
                         * @default rephrase
                         * @enum {string}
                         */
                        target_tone?: "warmer" | "shorter" | "clearer" | "rephrase";
                    };
                };
            };
            responses: {
                /** @description Polished text. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TextGenResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Hope Programme activity taxonomy.
         *
         *     "Emotions" was removed on 2026-05-27 — it had zero training pairs after dataset cleaning, so the LoRA cannot draft for it without hallucinating. /generate returns 422 if "Emotions" is supplied. Dashboards should still surface Emotions posts in the activity timeline but not invoke this API for them.
         *
         *     "Discussion" (forum posts) was added 2026-05-29 and behaves differently from the three structured activity types: /generate returns a SINGLE warm reply rather than 2-3 persona variants, and the caller should supply `thread_context` so the model can see the conversation it is answering. Forum replies are drafted zero-shot — the current adapters have no Discussion training pairs — so treat their quality as lower-confidence than activity drafts.
         * @enum {string}
         */
        ActivityType: "GoalSetting" | "Gratitude" | "MyHOPE" | "Discussion";
        /**
         * @description Draft style. Locked by the legacy risk-dashboard contract.
         * @enum {string}
         */
        Persona: "Empathetic" | "Action-oriented" | "Goal-oriented";
        /**
         * @description Display label paired with `Persona`. Locked by dashboard contract.
         * @enum {string}
         */
        PersonaLabel: "Warm personal check-in" | "Small next-step nudge" | "Goal-focused support";
        /**
         * @description Optional engagement-fingerprint inputs. **Weekly cadence** — the
         *     `engagement_ml` model recomputes scores once per week per
         *     (participant, week_number). The dashboard caches scores for the week
         *     and re-evaluates at week boundaries. Fields here may therefore be
         *     up to ~7 days stale relative to the current post — by design.
         *
         *     Sourced from
         *     `engagement_ml`'s `cumulative_features_panel.parquet`
         *     (weekly snapshot) or computed at the next week boundary by their
         *     `:8000/predict` call. When present, a one-line natural-language
         *     summary is injected into the draft prompt.
         *
         *     Stale-by-design contrast: the memory store (participant writing
         *     history) is hydrated in real-time via webhook on every new post,
         *     while the dropout fingerprint is intentionally weekly. The two
         *     signals coexist with different freshness characteristics.
         */
        EngagementSignals: {
            /** Format: float */
            days_since_last_login?: number;
            /** Format: float */
            days_since_last_activity?: number;
            /** Format: float */
            current_inactive_streak?: number;
            /** Format: float */
            engagement_slope?: number;
            /** Format: float */
            engagement_intensity?: number;
            cum_login_count?: number;
            cum_activity_count?: number;
            cum_unique_pages?: number;
            /** @enum {integer} */
            wrote_first_week_binary?: 0 | 1;
            /** @enum {integer} */
            received_comment_first_week_binary?: 0 | 1;
            /** Format: float */
            dropout_risk?: number;
            /** @enum {string} */
            risk_level?: "low" | "medium" | "high";
        };
        /**
         * @description Request body for `POST /generate`, sent by the HOPE MOVE platform
         *     (or the `hope-dashboard` app on its behalf): the participant's post
         *     plus the identifiers needed for memory-augmented generation.
         */
        RichGenerateRequest: {
            /** @description Platform user_id. */
            participant_id: number;
            /** @description Platform cohort.id (e.g. 1680 for IIH-COH12-110226). */
            cohort_id: number;
            /** @description Platform module.id (e.g. 337 for IIH 2025 V1). */
            module_id?: number;
            /** @description Programme week the post belongs to (1-based). Advisory only — it is not part of the prompt; memory retrieval and engagement enrichment key off participant_id/cohort_id. Carried so log lines and HITL rows can be grouped by week. */
            week_number?: number;
            activity_id?: number;
            activity_type?: components["schemas"]["ActivityType"];
            post_text: string;
            /** @description Used in the Empathetic-style lead-in. */
            display_name?: string;
            engagement?: components["schemas"]["EngagementSignals"];
            /** @description Pre-rendered forum thread — topic opening plus the ordered replies preceding the post being answered — supplied by the caller when `activity_type` is `Discussion`. This is what makes a forum reply coherent: without it the model answers a single post with no sight of the conversation. Ignored for every other activity_type. The caller is responsible for trimming to the 4000-character cap. */
            thread_context?: string;
        };
        Draft: {
            persona: components["schemas"]["Persona"];
            label: components["schemas"]["PersonaLabel"];
            /** @description 1–3 sentence draft. Single facilitator turn. */
            body: string;
            /**
             * Format: uuid
             * @description Quote on subsequent `/thumb` and `/event` calls.
             */
            draft_id: string;
            /** @description Optional MI-scorer per-draft summary (debug). */
            mi_signature?: {
                /** Format: float */
                open_question_ratio?: number;
                /** Format: float */
                reflection_density?: number;
                /** Format: float */
                prescriptive_density?: number;
            };
            /**
             * @description MI-policy hard-rule violations still present after regeneration
             *     (diagnostic language, medication/dosage, URLs). Absent or null
             *     when the draft is clean. The dashboard shows these as a warning
             *     so a facilitator never sends a flagged draft unknowingly.
             */
            mi_violations?: string[] | null;
            /**
             * @description Whether the draft refers only to what the participant's post
             *     says. `ungrounded` means it mentions something the post does not
             *     say (a person, event, place, photo, outcome or feeling) and every
             *     regeneration did too; the dashboard warns so the facilitator
             *     checks it against the post before sending. `unchecked` means the
             *     check is off or gave no usable answer — it is not an approval.
             *     Absent from service versions that predate the check.
             * @enum {string|null}
             */
            grounding?: "grounded" | "ungrounded" | "unchecked" | null;
        };
        GenerateResponse: {
            /**
             * @description 1 draft for a forum/Discussion reply, 2 for Gratitude
             *     (Empathetic + Goal-oriented; Action-oriented dropped per the
             *     HOPE manual), 3 for other activity posts.
             */
            drafts: components["schemas"]["Draft"][];
            /**
             * Format: uuid
             * @description Links the drafts; quote on `/event`.
             */
            draft_set_id: string;
            /** @description false on cold-start (no prior posts for this participant). */
            memory_used?: boolean;
            /** @description false when no engagement signals provided. */
            engagement_used?: boolean;
            /**
             * @description Set when input safety filter blocks the post (crisis lexicon
             *     match). Drafts array is empty; client should render the
             *     signposting message instead.
             */
            safety_signposting?: string | null;
            /** @example finetuned_slm_Qwen2.5-1.5B_hope-only */
            model_version?: string;
            /** Format: date-time */
            generated_at: string;
        };
        /** @enum {string} */
        MemoryRole: "participant_post" | "facilitator_reply";
        /** @enum {string} */
        MemorySource: "platform_webhook" | "platform_backfill" | "json_reconcile" | "hitl";
        MemoryPostRequest: {
            /** @description Idempotency key (combined with role=participant_post). */
            activity_id: number;
            participant_id: number;
            cohort_id: number;
            module_id: number;
            activity_type?: components["schemas"]["ActivityType"];
            text: string;
            /** Format: date-time */
            recorded_at: string;
            display_name?: string | null;
            source: components["schemas"]["MemorySource"];
        };
        MemoryReplyRequest: {
            /** @description Idempotency key (combined with role=facilitator_reply). */
            comment_id: number;
            /** @description The post being replied to. */
            activity_id: number;
            participant_id: number;
            cohort_id: number;
            facilitator_id: string;
            text: string;
            /** Format: date-time */
            recorded_at: string;
            source: components["schemas"]["MemorySource"];
        };
        MemoryWriteResponse: {
            /** @enum {string} */
            status: "stored" | "deduped";
            memory_id?: number;
        };
        MemoryBatchRequest: {
            items: ((components["schemas"]["MemoryPostRequest"] & {
                /** @constant */
                kind: "post";
            }) | (components["schemas"]["MemoryReplyRequest"] & {
                /** @constant */
                kind: "reply";
            }))[];
        };
        MemoryBatchResponse: {
            stored: number;
            deduped: number;
            errors: {
                index: number;
                reason: string;
            }[];
        };
        /** @description Row returned by debug `/memory/{participant_id}`. */
        MemoryEntry: {
            memory_id?: number;
            participant_id?: number;
            cohort_id?: number;
            /** Format: date-time */
            ts?: string;
            activity_id?: number | null;
            activity_type?: components["schemas"]["ActivityType"] | null;
            role?: components["schemas"]["MemoryRole"];
            text?: string;
        };
        ThumbRequest: {
            /** Format: uuid */
            draft_id: string;
            /** @enum {string} */
            label: "up" | "down";
            facilitator_id: string;
        };
        /** @enum {string} */
        EventAction: "accept" | "edit" | "reject" | "flag";
        EventRequest: {
            /** Format: uuid */
            draft_set_id: string;
            /**
             * Format: uuid
             * @description The draft variant the facilitator acted on. For action=accept or
             *     action=edit, the same persona's text is also written to memory
             *     via the HITL fast-path so subsequent /generate calls see it
             *     without waiting for the platform webhook.
             */
            chosen_draft_id: string;
            action: components["schemas"]["EventAction"];
            /**
             * @description Required when action ∈ {accept, edit}. Forbidden otherwise.
             *     For action=accept this should equal the draft body verbatim;
             *     for action=edit it is the facilitator's edited text.
             */
            sent_text?: string | null;
            facilitator_id: string;
            /** @description Required when action=flag. */
            flag_reason?: string | null;
        };
        AckResponse: {
            /** @enum {string} */
            status: "ok";
        };
        HealthResponse: {
            /** @enum {string} */
            status: "healthy" | "degraded";
            model_loaded?: boolean;
            /** @enum {string} */
            memory_db?: "ok" | "missing" | "error";
            /** @enum {string} */
            dropout_api?: "reachable" | "unreachable";
            /**
             * @description Decodes running or queued. One process serves one model, so
             *     a value above 1 means callers are waiting on each other.
             * @default 0
             */
            generation_queue_depth: number;
            /** Format: date-time */
            timestamp?: string;
        };
        VersionResponse: {
            /** @example 0.1.0 */
            service_version: string;
            /** @example finetuned_slm_Qwen2.5-1.5B_hope-only */
            model_version: string;
            /** Format: date-time */
            deployed_at: string;
            commit_sha?: string;
        };
        TextGenResponse: {
            /** @description The generated / polished text (single string). */
            text: string;
            /** @enum {string} */
            task: "summary" | "coaching" | "polish";
            model_version: string;
            /** Format: date-time */
            generated_at: string;
        };
        ErrorResponse: {
            detail: string;
            /** @example invalid_signature */
            code?: string;
        };
    };
    responses: {
        /** @description HMAC signature missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Validation error. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request body failed Pydantic validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
